# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.utils


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.AlterField(
            model_name='registration',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.TextField(default=registration.utils.password_default),
        ),
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.TextField(default=None),
        ),
    ]
